// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  configuracion_fondo: dynamic(() => import("./ConfiguracionFondo")),
  grid_caracteristicas: dynamic(() => import("./GridCaracteristicas")),
  grid_partners: dynamic(() => import("./GridPartners")),
  hero: dynamic(() => import("./Hero")),
  linkedin_post: dynamic(() => import("./LinkedInPost")),
  producto_destacado: dynamic(() => import("./ProductoDestacado")),
  seccion_contenido: dynamic(() => import("./SeccionContenido")),
  seccion_informativa: dynamic(() => import("./SeccionInformativa")),
  video_section: dynamic(() => import("./VideoSection")),
};
